# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CampaignState.proto

require 'google/protobuf'


Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "CampaignState" do
    optional :Name, :string, 1
    repeated :Airfields, :message, 2, "CampaignSupplyPoint"
    repeated :Objectives, :message, 3, "CampaignSupplyPoint"
    optional :FrontLine, :message, 4, "CampaignFrontLine"
    optional :Day, :message, 5, "CampaignDay"
    optional :PlayAreaBoundaryNorthWest, :message, 6, "CampaignPosition"
    optional :PlayAreaBoundarySouthEast, :message, 7, "CampaignPosition"
  end
  add_message "CampaignAirfield" do
    repeated :Blocks, :message, 1, "CampaignBlock"
  end
  add_message "CampaignBlock" do
    optional :Model, :string, 1
    optional :Health, :double, 2
    optional :DestroyedComponents, :int32, 3
    optional :Position, :message, 4, "CampaignPosition"
  end
  add_message "CampaignCountry" do
    optional :Name, :string, 1
    optional :Code, :int32, 2
  end
  add_message "CampaignDay" do
    optional :Year, :int32, 1
    optional :Month, :int32, 2
    optional :Day, :int32, 3
    optional :DayInCampaign, :int32, 4
  end
  add_message "CampaignFrontLine" do
    optional :Name, :string, 1
    repeated :PositionsInFrontLine, :message, 2, "CampaignPosition"
  end
  add_message "CampaignObjective" do
    optional :Type, :enum, 1, "CampaignObjectiveType"
    repeated :Blocks, :message, 2, "CampaignBlock"
  end
  add_message "CampaignPosition" do
    optional :X, :double, 1
    optional :Y, :double, 2
    optional :Z, :double, 3
  end
  add_message "CampaignSupplyPoint" do
    optional :Name, :string, 1
    optional :Position, :message, 2, "CampaignPosition"
    optional :Country, :message, 3, "CampaignCountry"
    optional :SupplyLevel, :int32, 4
    optional :ActiveToday, :bool, 5
    oneof :subtype do
      optional :CampaignAirfield, :message, 11, "CampaignAirfield"
      optional :CampaignObjective, :message, 12, "CampaignObjective"
    end
  end
  add_enum "CampaignObjectiveType" do
    value :UNKNOWN, 0
    value :STRATEGIC, 1
    value :POP_UP, 2
  end
end

CampaignState = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignState").msgclass
CampaignAirfield = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignAirfield").msgclass
CampaignBlock = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignBlock").msgclass
CampaignCountry = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignCountry").msgclass
CampaignDay = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignDay").msgclass
CampaignFrontLine = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignFrontLine").msgclass
CampaignObjective = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignObjective").msgclass
CampaignPosition = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignPosition").msgclass
CampaignSupplyPoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignSupplyPoint").msgclass
CampaignObjectiveType = Google::Protobuf::DescriptorPool.generated_pool.lookup("CampaignObjectiveType").enummodule
