# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: velikie-campaign-day-49-events.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "campaign_library.protobuf.TimeSpan" do
    optional :value, :sint64, 1
    optional :scale, :enum, 2, "campaign_library.protobuf.TimeSpan.TimeSpanScale"
  end
  add_enum "campaign_library.protobuf.TimeSpan.TimeSpanScale" do
    value :DAYS, 0
    value :HOURS, 1
    value :MINUTES, 2
    value :SECONDS, 3
    value :MILLISECONDS, 4
    value :MINMAX, 15
  end
  add_message "campaign_library.protobuf.DateTime" do
    optional :value, :sint64, 1
    optional :scale, :enum, 2, "campaign_library.protobuf.DateTime.TimeSpanScale"
  end
  add_enum "campaign_library.protobuf.DateTime.TimeSpanScale" do
    value :DAYS, 0
    value :HOURS, 1
    value :MINUTES, 2
    value :SECONDS, 3
    value :MILLISECONDS, 4
    value :MINMAX, 15
  end
  add_message "campaign_library.protobuf.Guid" do
    optional :lo, :fixed64, 1
    optional :hi, :fixed64, 2
  end
  add_message "campaign_library.protobuf.Decimal" do
    optional :lo, :uint64, 1
    optional :hi, :uint32, 2
    optional :signScale, :sint32, 3
  end
  add_message "campaign_library.protobuf.Aircraft" do
    optional :Type, :string, 1
    optional :Pilot, :message, 2, "campaign_library.protobuf.BotPilot"
  end
  add_message "campaign_library.protobuf.BotPilot" do
    optional :Id, :int64, 1
  end
  add_message "campaign_library.protobuf.CampaignCountry" do
    optional :Name, :string, 1
    optional :Code, :int32, 2
  end
  add_message "campaign_library.protobuf.CampaignDayStart" do
    optional :DayStartTime, :message, 1, "campaign_library.protobuf.DateTime"
    optional :DayInCampaign, :int32, 2
  end
  add_message "campaign_library.protobuf.CampaignPosition" do
    optional :X, :double, 1
    optional :Y, :double, 2
    optional :Z, :double, 3
  end
  add_message "campaign_library.protobuf.Damage" do
    optional :Amount, :double, 1
    optional :Attacker, :message, 2, "campaign_library.protobuf.MissionObject"
    optional :Victim, :message, 3, "campaign_library.protobuf.MissionObject"
    optional :Position, :message, 4, "campaign_library.protobuf.CampaignPosition"
  end
  add_message "campaign_library.protobuf.Disconnect" do
    optional :Aircraft, :message, 1, "campaign_library.protobuf.MissionObject"
    optional :Position, :message, 2, "campaign_library.protobuf.CampaignPosition"
  end
  add_message "campaign_library.protobuf.Kill" do
    optional :Attacker, :message, 1, "campaign_library.protobuf.MissionObject"
    optional :Victim, :message, 2, "campaign_library.protobuf.MissionObject"
    optional :Position, :message, 3, "campaign_library.protobuf.CampaignPosition"
  end
  add_message "campaign_library.protobuf.Landing" do
    optional :Aircraft, :message, 1, "campaign_library.protobuf.MissionObject"
    optional :Position, :message, 2, "campaign_library.protobuf.CampaignPosition"
  end
  add_message "campaign_library.protobuf.MissionEvent" do
    optional :EventTime, :message, 10, "campaign_library.protobuf.DateTime"
    oneof :subtype do
      optional :Kill, :message, 1, "campaign_library.protobuf.Kill"
      optional :Damage, :message, 2, "campaign_library.protobuf.Damage"
      optional :Spawn, :message, 3, "campaign_library.protobuf.Spawn"
      optional :PlayerSpawn, :message, 4, "campaign_library.protobuf.PlayerSpawn"
      optional :Landing, :message, 5, "campaign_library.protobuf.Landing"
      optional :Takeoff, :message, 6, "campaign_library.protobuf.Takeoff"
      optional :SortieEnd, :message, 7, "campaign_library.protobuf.SortieEnd"
      optional :Disconnect, :message, 8, "campaign_library.protobuf.Disconnect"
      optional :CampaignDayStart, :message, 9, "campaign_library.protobuf.CampaignDayStart"
    end
  end
  add_message "campaign_library.protobuf.MissionEvents" do
    repeated :Events, :message, 1, "campaign_library.protobuf.MissionEvent"
  end
  add_message "campaign_library.protobuf.MissionObject" do
    optional :Id, :int64, 1
    optional :Model, :string, 2
    optional :Country, :message, 3, "campaign_library.protobuf.CampaignCountry"
    oneof :subtype do
      optional :StaticBlock, :message, 4, "campaign_library.protobuf.StaticBlock"
      optional :Aircraft, :message, 5, "campaign_library.protobuf.Aircraft"
      optional :Vehicle, :message, 6, "campaign_library.protobuf.Vehicle"
    end
  end
  add_message "campaign_library.protobuf.PlayerSpawn" do
    optional :Aircraft, :message, 1, "campaign_library.protobuf.MissionObject"
    optional :Position, :message, 2, "campaign_library.protobuf.CampaignPosition"
    optional :Country, :message, 3, "campaign_library.protobuf.CampaignCountry"
    optional :PlayerName, :string, 4
    optional :PlayerId, :string, 5
    optional :NumBombs, :int32, 6
    optional :NumRockets, :int32, 7
    optional :PayloadId, :int32, 8
    optional :Fuel, :double, 9
    optional :Skin, :string, 10
    optional :WeaponMods, :string, 11
  end
  add_message "campaign_library.protobuf.SortieEnd" do
    optional :Aircraft, :message, 1, "campaign_library.protobuf.MissionObject"
    optional :Position, :message, 2, "campaign_library.protobuf.CampaignPosition"
  end
  add_message "campaign_library.protobuf.Spawn" do
    optional :ThingSpawned, :message, 1, "campaign_library.protobuf.MissionObject"
    optional :Parent, :message, 2, "campaign_library.protobuf.MissionObject"
    optional :Country, :message, 3, "campaign_library.protobuf.CampaignCountry"
    optional :Position, :message, 4, "campaign_library.protobuf.CampaignPosition"
  end
  add_message "campaign_library.protobuf.StaticBlock" do
    optional :SupplyPointId, :int32, 1
    optional :Position, :message, 2, "campaign_library.protobuf.CampaignPosition"
    optional :Category, :string, 3
  end
  add_message "campaign_library.protobuf.Takeoff" do
    optional :Aircraft, :message, 1, "campaign_library.protobuf.MissionObject"
    optional :Position, :message, 2, "campaign_library.protobuf.CampaignPosition"
  end
  add_message "campaign_library.protobuf.Vehicle" do
    optional :Category, :string, 1
  end
end

module CampaignLibrary
  module Protobuf
    TimeSpan = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.TimeSpan").msgclass
    TimeSpan::TimeSpanScale = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.TimeSpan.TimeSpanScale").enummodule
    DateTime = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.DateTime").msgclass
    DateTime::TimeSpanScale = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.DateTime.TimeSpanScale").enummodule
    Guid = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Guid").msgclass
    Decimal = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Decimal").msgclass
    Aircraft = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Aircraft").msgclass
    BotPilot = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.BotPilot").msgclass
    CampaignCountry = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.CampaignCountry").msgclass
    CampaignDayStart = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.CampaignDayStart").msgclass
    CampaignPosition = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.CampaignPosition").msgclass
    Damage = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Damage").msgclass
    Disconnect = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Disconnect").msgclass
    Kill = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Kill").msgclass
    Landing = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Landing").msgclass
    MissionEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.MissionEvent").msgclass
    MissionEvents = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.MissionEvents").msgclass
    MissionObject = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.MissionObject").msgclass
    PlayerSpawn = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.PlayerSpawn").msgclass
    SortieEnd = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.SortieEnd").msgclass
    Spawn = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Spawn").msgclass
    StaticBlock = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.StaticBlock").msgclass
    Takeoff = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Takeoff").msgclass
    Vehicle = Google::Protobuf::DescriptorPool.generated_pool.lookup("campaign_library.protobuf.Vehicle").msgclass
  end
end
