describe MissionCards::DeckGenerator do
  include_context "app config"

  subject { MissionCards::DeckGenerator.new(MissionCards::DeckConfiguration.new) }

  describe 'loading deck config' do
    it 'provides actionable targets' do
      attackable_targets = subject.attackable_targets('allies').keys

      expect(attackable_targets).to match_array [
        "bases", "industrial buildings", "trains", 
        "ground units", "bridges", "tanks", "coastal logistics"
      ]
    end

    it 'provides available planes' do
      available_planes = subject.available_planes(raf).keys

      expect(available_planes).to match_array ["a20b", "p47d22", "p51b5", "spitfiremkixe", "typhoonmkib"]
    end
  end

  describe 'selecting card templates' do
    it 'selects the right card templates' do
      expect(subject.actionable_card_templates(raf).map(&:title)).to match_array [
        "Close Air Support",
        "Factory Strike",
        "Fighter Bomber Attack",
        "Industrial Attack",
        "Industrial Level Bomb",
        "Train Hunter",
        "Train Yard Level Bomb",
        "Bridge Attack",
        "Bridge Level Bomb",
        "Tank Busters",
        "Tank Level Bomb",
      ]
    end
  end

  describe '#generate_for_airforce!' do
    it 'populates the cards table for the given airforce' do
      cards = subject.generate_for_airforce!(raf)
      result = cards.map { |card| [card.title, card.area_of_operation, card.airfield, card.plane] }

      expect(result).to match_array [["Factory Strike", "Veliki Rail Terminal", "Nasva", "a20b"],
        ["Factory Strike", "Veliki Rail Terminal", "Zabel Ye", "a20b"],
        ["Factory Strike", "Veliki Rail Terminal", "Novo", "a20b"],
        ["Factory Strike", "Sopki Railyard", "Nasva", "a20b"],
        ["Factory Strike", "Sopki Railyard", "Zabel Ye", "a20b"],
        ["Factory Strike", "Sopki Railyard", "Novo", "a20b"],
        ["Factory Strike", "Toropets Rail", "Nasva", "a20b"],
        ["Factory Strike", "Toropets Rail", "Zabel Ye", "a20b"],
        ["Factory Strike", "Toropets Rail", "Novo", "a20b"],
        ["Factory Strike", "Bubnova Rail", "Nasva", "a20b"],
        ["Factory Strike", "Bubnova Rail", "Zabel Ye", "a20b"],
        ["Factory Strike", "Bubnova Rail", "Novo", "a20b"],
        ["Factory Strike", "Manistrova Rail Yard", "Nasva", "a20b"],
        ["Factory Strike", "Manistrova Rail Yard", "Zabel Ye", "a20b"],
        ["Factory Strike", "Manistrova Rail Yard", "Novo", "a20b"],
        ["Factory Strike", "Veliki Rail Terminal", "Nasva", "p51b5"],
        ["Factory Strike", "Veliki Rail Terminal", "Zabel Ye", "p51b5"],
        ["Factory Strike", "Veliki Rail Terminal", "Novo", "p51b5"],
        ["Factory Strike", "Sopki Railyard", "Nasva", "p51b5"],
        ["Factory Strike", "Sopki Railyard", "Zabel Ye", "p51b5"],
        ["Factory Strike", "Sopki Railyard", "Novo", "p51b5"],
        ["Factory Strike", "Toropets Rail", "Nasva", "p51b5"],
        ["Factory Strike", "Toropets Rail", "Zabel Ye", "p51b5"],
        ["Factory Strike", "Toropets Rail", "Novo", "p51b5"],
        ["Factory Strike", "Bubnova Rail", "Nasva", "p51b5"],
        ["Factory Strike", "Bubnova Rail", "Zabel Ye", "p51b5"],
        ["Factory Strike", "Bubnova Rail", "Novo", "p51b5"],
        ["Factory Strike", "Manistrova Rail Yard", "Nasva", "p51b5"],
        ["Factory Strike", "Manistrova Rail Yard", "Zabel Ye", "p51b5"],
        ["Factory Strike", "Manistrova Rail Yard", "Novo", "p51b5"],
        ["Factory Strike", "Veliki Rail Terminal", "Nasva", "typhoonmkib"],
        ["Factory Strike", "Veliki Rail Terminal", "Zabel Ye", "typhoonmkib"],
        ["Factory Strike", "Veliki Rail Terminal", "Novo", "typhoonmkib"],
        ["Factory Strike", "Sopki Railyard", "Nasva", "typhoonmkib"],
        ["Factory Strike", "Sopki Railyard", "Zabel Ye", "typhoonmkib"],
        ["Factory Strike", "Sopki Railyard", "Novo", "typhoonmkib"],
        ["Factory Strike", "Toropets Rail", "Nasva", "typhoonmkib"],
        ["Factory Strike", "Toropets Rail", "Zabel Ye", "typhoonmkib"],
        ["Factory Strike", "Toropets Rail", "Novo", "typhoonmkib"],
        ["Factory Strike", "Bubnova Rail", "Nasva", "typhoonmkib"],
        ["Factory Strike", "Bubnova Rail", "Zabel Ye", "typhoonmkib"],
        ["Factory Strike", "Bubnova Rail", "Novo", "typhoonmkib"],
        ["Factory Strike", "Manistrova Rail Yard", "Nasva", "typhoonmkib"],
        ["Factory Strike", "Manistrova Rail Yard", "Zabel Ye", "typhoonmkib"],
        ["Factory Strike", "Manistrova Rail Yard", "Novo", "typhoonmkib"],
        ["Factory Strike", "Veliki Rail Terminal", "Nasva", "spitfiremkixe"],
        ["Factory Strike", "Veliki Rail Terminal", "Zabel Ye", "spitfiremkixe"],
        ["Factory Strike", "Veliki Rail Terminal", "Novo", "spitfiremkixe"],
        ["Factory Strike", "Sopki Railyard", "Nasva", "spitfiremkixe"],
        ["Factory Strike", "Sopki Railyard", "Zabel Ye", "spitfiremkixe"],
        ["Factory Strike", "Sopki Railyard", "Novo", "spitfiremkixe"],
        ["Factory Strike", "Toropets Rail", "Nasva", "spitfiremkixe"],
        ["Factory Strike", "Toropets Rail", "Zabel Ye", "spitfiremkixe"],
        ["Factory Strike", "Toropets Rail", "Novo", "spitfiremkixe"],
        ["Factory Strike", "Bubnova Rail", "Nasva", "spitfiremkixe"],
        ["Factory Strike", "Bubnova Rail", "Zabel Ye", "spitfiremkixe"],
        ["Factory Strike", "Bubnova Rail", "Novo", "spitfiremkixe"],
        ["Factory Strike", "Manistrova Rail Yard", "Nasva", "spitfiremkixe"],
        ["Factory Strike", "Manistrova Rail Yard", "Zabel Ye", "spitfiremkixe"],
        ["Factory Strike", "Manistrova Rail Yard", "Novo", "spitfiremkixe"],
        ["Factory Strike", "Veliki Rail Terminal", "Zabel Ye", "p47d22"],
        ["Factory Strike", "Sopki Railyard", "Zabel Ye", "p47d22"],
        ["Factory Strike", "Toropets Rail", "Zabel Ye", "p47d22"],
        ["Factory Strike", "Bubnova Rail", "Zabel Ye", "p47d22"],
        ["Factory Strike", "Manistrova Rail Yard", "Zabel Ye", "p47d22"],
        ["Industrial Attack", "Veliki Rail Terminal", "Nasva", "a20b"],
        ["Industrial Attack", "Veliki Rail Terminal", "Zabel Ye", "a20b"],
        ["Industrial Attack", "Veliki Rail Terminal", "Novo", "a20b"],
        ["Industrial Attack", "Sopki Railyard", "Nasva", "a20b"],
        ["Industrial Attack", "Sopki Railyard", "Zabel Ye", "a20b"],
        ["Industrial Attack", "Sopki Railyard", "Novo", "a20b"],
        ["Industrial Attack", "Toropets Rail", "Nasva", "a20b"],
        ["Industrial Attack", "Toropets Rail", "Zabel Ye", "a20b"],
        ["Industrial Attack", "Toropets Rail", "Novo", "a20b"],
        ["Industrial Attack", "Bubnova Rail", "Nasva", "a20b"],
        ["Industrial Attack", "Bubnova Rail", "Zabel Ye", "a20b"],
        ["Industrial Attack", "Bubnova Rail", "Novo", "a20b"],
        ["Industrial Attack", "Manistrova Rail Yard", "Nasva", "a20b"],
        ["Industrial Attack", "Manistrova Rail Yard", "Zabel Ye", "a20b"],
        ["Industrial Attack", "Manistrova Rail Yard", "Novo", "a20b"],
        ["Industrial Attack", "Veliki Rail Terminal", "Nasva", "p51b5"],
        ["Industrial Attack", "Veliki Rail Terminal", "Zabel Ye", "p51b5"],
        ["Industrial Attack", "Veliki Rail Terminal", "Novo", "p51b5"],
        ["Industrial Attack", "Sopki Railyard", "Nasva", "p51b5"],
        ["Industrial Attack", "Sopki Railyard", "Zabel Ye", "p51b5"],
        ["Industrial Attack", "Sopki Railyard", "Novo", "p51b5"],
        ["Industrial Attack", "Toropets Rail", "Nasva", "p51b5"],
        ["Industrial Attack", "Toropets Rail", "Zabel Ye", "p51b5"],
        ["Industrial Attack", "Toropets Rail", "Novo", "p51b5"],
        ["Industrial Attack", "Bubnova Rail", "Nasva", "p51b5"],
        ["Industrial Attack", "Bubnova Rail", "Zabel Ye", "p51b5"],
        ["Industrial Attack", "Bubnova Rail", "Novo", "p51b5"],
        ["Industrial Attack", "Manistrova Rail Yard", "Nasva", "p51b5"],
        ["Industrial Attack", "Manistrova Rail Yard", "Zabel Ye", "p51b5"],
        ["Industrial Attack", "Manistrova Rail Yard", "Novo", "p51b5"],
        ["Industrial Attack", "Veliki Rail Terminal", "Nasva", "typhoonmkib"],
        ["Industrial Attack", "Veliki Rail Terminal", "Zabel Ye", "typhoonmkib"],
        ["Industrial Attack", "Veliki Rail Terminal", "Novo", "typhoonmkib"],
        ["Industrial Attack", "Sopki Railyard", "Nasva", "typhoonmkib"],
        ["Industrial Attack", "Sopki Railyard", "Zabel Ye", "typhoonmkib"],
        ["Industrial Attack", "Sopki Railyard", "Novo", "typhoonmkib"],
        ["Industrial Attack", "Toropets Rail", "Nasva", "typhoonmkib"],
        ["Industrial Attack", "Toropets Rail", "Zabel Ye", "typhoonmkib"],
        ["Industrial Attack", "Toropets Rail", "Novo", "typhoonmkib"],
        ["Industrial Attack", "Bubnova Rail", "Nasva", "typhoonmkib"],
        ["Industrial Attack", "Bubnova Rail", "Zabel Ye", "typhoonmkib"],
        ["Industrial Attack", "Bubnova Rail", "Novo", "typhoonmkib"],
        ["Industrial Attack", "Manistrova Rail Yard", "Nasva", "typhoonmkib"],
        ["Industrial Attack", "Manistrova Rail Yard", "Zabel Ye", "typhoonmkib"],
        ["Industrial Attack", "Manistrova Rail Yard", "Novo", "typhoonmkib"],
        ["Industrial Attack", "Veliki Rail Terminal", "Nasva", "spitfiremkixe"],
        ["Industrial Attack", "Veliki Rail Terminal", "Zabel Ye", "spitfiremkixe"],
        ["Industrial Attack", "Veliki Rail Terminal", "Novo", "spitfiremkixe"],
        ["Industrial Attack", "Sopki Railyard", "Nasva", "spitfiremkixe"],
        ["Industrial Attack", "Sopki Railyard", "Zabel Ye", "spitfiremkixe"],
        ["Industrial Attack", "Sopki Railyard", "Novo", "spitfiremkixe"],
        ["Industrial Attack", "Toropets Rail", "Nasva", "spitfiremkixe"],
        ["Industrial Attack", "Toropets Rail", "Zabel Ye", "spitfiremkixe"],
        ["Industrial Attack", "Toropets Rail", "Novo", "spitfiremkixe"],
        ["Industrial Attack", "Bubnova Rail", "Nasva", "spitfiremkixe"],
        ["Industrial Attack", "Bubnova Rail", "Zabel Ye", "spitfiremkixe"],
        ["Industrial Attack", "Bubnova Rail", "Novo", "spitfiremkixe"],
        ["Industrial Attack", "Manistrova Rail Yard", "Nasva", "spitfiremkixe"],
        ["Industrial Attack", "Manistrova Rail Yard", "Zabel Ye", "spitfiremkixe"],
        ["Industrial Attack", "Manistrova Rail Yard", "Novo", "spitfiremkixe"],
        ["Industrial Attack", "Veliki Rail Terminal", "Zabel Ye", "p47d22"],
        ["Industrial Attack", "Sopki Railyard", "Zabel Ye", "p47d22"],
        ["Industrial Attack", "Toropets Rail", "Zabel Ye", "p47d22"],
        ["Industrial Attack", "Bubnova Rail", "Zabel Ye", "p47d22"],
        ["Industrial Attack", "Manistrova Rail Yard", "Zabel Ye", "p47d22"],
        ["Bridge Attack", "Rojnova Bridges", "Nasva", "a20b"],
        ["Bridge Attack", "Rojnova Bridges", "Zabel Ye", "a20b"],
        ["Bridge Attack", "Rojnova Bridges", "Novo", "a20b"],
        ["Bridge Attack", "Rojnova Bridges", "Nasva", "p51b5"],
        ["Bridge Attack", "Rojnova Bridges", "Zabel Ye", "p51b5"],
        ["Bridge Attack", "Rojnova Bridges", "Novo", "p51b5"],
        ["Bridge Attack", "Rojnova Bridges", "Nasva", "typhoonmkib"],
        ["Bridge Attack", "Rojnova Bridges", "Zabel Ye", "typhoonmkib"],
        ["Bridge Attack", "Rojnova Bridges", "Novo", "typhoonmkib"],
        ["Bridge Attack", "Rojnova Bridges", "Nasva", "spitfiremkixe"],
        ["Bridge Attack", "Rojnova Bridges", "Zabel Ye", "spitfiremkixe"],
        ["Bridge Attack", "Rojnova Bridges", "Novo", "spitfiremkixe"],
        ["Bridge Attack", "Rojnova Bridges", "Zabel Ye", "p47d22"],
        ["Train Hunter", "Veliki Rail Terminal", "Nasva", "p51b5"],
        ["Train Hunter", "Veliki Rail Terminal", "Zabel Ye", "p51b5"],
        ["Train Hunter", "Veliki Rail Terminal", "Novo", "p51b5"],
        ["Train Hunter", "Sopki Railyard", "Nasva", "p51b5"],
        ["Train Hunter", "Sopki Railyard", "Zabel Ye", "p51b5"],
        ["Train Hunter", "Sopki Railyard", "Novo", "p51b5"],
        ["Train Hunter", "Toropets Rail", "Nasva", "p51b5"],
        ["Train Hunter", "Toropets Rail", "Zabel Ye", "p51b5"],
        ["Train Hunter", "Toropets Rail", "Novo", "p51b5"],
        ["Train Hunter", "Bubnova Rail", "Nasva", "p51b5"],
        ["Train Hunter", "Bubnova Rail", "Zabel Ye", "p51b5"],
        ["Train Hunter", "Bubnova Rail", "Novo", "p51b5"],
        ["Train Hunter", "Manistrova Rail Yard", "Nasva", "p51b5"],
        ["Train Hunter", "Manistrova Rail Yard", "Zabel Ye", "p51b5"],
        ["Train Hunter", "Manistrova Rail Yard", "Novo", "p51b5"],
        ["Train Hunter", "Veliki Rail Terminal", "Nasva", "typhoonmkib"],
        ["Train Hunter", "Veliki Rail Terminal", "Zabel Ye", "typhoonmkib"],
        ["Train Hunter", "Veliki Rail Terminal", "Novo", "typhoonmkib"],
        ["Train Hunter", "Sopki Railyard", "Nasva", "typhoonmkib"],
        ["Train Hunter", "Sopki Railyard", "Zabel Ye", "typhoonmkib"],
        ["Train Hunter", "Sopki Railyard", "Novo", "typhoonmkib"],
        ["Train Hunter", "Toropets Rail", "Nasva", "typhoonmkib"],
        ["Train Hunter", "Toropets Rail", "Zabel Ye", "typhoonmkib"],
        ["Train Hunter", "Toropets Rail", "Novo", "typhoonmkib"],
        ["Train Hunter", "Bubnova Rail", "Nasva", "typhoonmkib"],
        ["Train Hunter", "Bubnova Rail", "Zabel Ye", "typhoonmkib"],
        ["Train Hunter", "Bubnova Rail", "Novo", "typhoonmkib"],
        ["Train Hunter", "Manistrova Rail Yard", "Nasva", "typhoonmkib"],
        ["Train Hunter", "Manistrova Rail Yard", "Zabel Ye", "typhoonmkib"],
        ["Train Hunter", "Manistrova Rail Yard", "Novo", "typhoonmkib"],
        ["Train Hunter", "Veliki Rail Terminal", "Nasva", "spitfiremkixe"],
        ["Train Hunter", "Veliki Rail Terminal", "Zabel Ye", "spitfiremkixe"],
        ["Train Hunter", "Veliki Rail Terminal", "Novo", "spitfiremkixe"],
        ["Train Hunter", "Sopki Railyard", "Nasva", "spitfiremkixe"],
        ["Train Hunter", "Sopki Railyard", "Zabel Ye", "spitfiremkixe"],
        ["Train Hunter", "Sopki Railyard", "Novo", "spitfiremkixe"],
        ["Train Hunter", "Toropets Rail", "Nasva", "spitfiremkixe"],
        ["Train Hunter", "Toropets Rail", "Zabel Ye", "spitfiremkixe"],
        ["Train Hunter", "Toropets Rail", "Novo", "spitfiremkixe"],
        ["Train Hunter", "Bubnova Rail", "Nasva", "spitfiremkixe"],
        ["Train Hunter", "Bubnova Rail", "Zabel Ye", "spitfiremkixe"],
        ["Train Hunter", "Bubnova Rail", "Novo", "spitfiremkixe"],
        ["Train Hunter", "Manistrova Rail Yard", "Nasva", "spitfiremkixe"],
        ["Train Hunter", "Manistrova Rail Yard", "Zabel Ye", "spitfiremkixe"],
        ["Train Hunter", "Manistrova Rail Yard", "Novo", "spitfiremkixe"],
        ["Train Hunter", "Veliki Rail Terminal", "Zabel Ye", "p47d22"],
        ["Train Hunter", "Sopki Railyard", "Zabel Ye", "p47d22"],
        ["Train Hunter", "Toropets Rail", "Zabel Ye", "p47d22"],
        ["Train Hunter", "Bubnova Rail", "Zabel Ye", "p47d22"],
        ["Train Hunter", "Manistrova Rail Yard", "Zabel Ye", "p47d22"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Nasva", "p51b5"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Zabel Ye", "p51b5"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Novo", "p51b5"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Nasva", "p51b5"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Zabel Ye", "p51b5"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Novo", "p51b5"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Nasva", "p51b5"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Zabel Ye", "p51b5"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Novo", "p51b5"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Nasva", "p51b5"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Zabel Ye", "p51b5"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Novo", "p51b5"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Nasva", "p51b5"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Zabel Ye", "p51b5"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Novo", "p51b5"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Nasva", "p51b5"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Zabel Ye", "p51b5"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Novo", "p51b5"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Nasva", "p51b5"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Zabel Ye", "p51b5"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Novo", "p51b5"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Nasva", "typhoonmkib"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Zabel Ye", "typhoonmkib"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Novo", "typhoonmkib"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Nasva", "typhoonmkib"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Zabel Ye", "typhoonmkib"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Novo", "typhoonmkib"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Nasva", "typhoonmkib"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Zabel Ye", "typhoonmkib"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Novo", "typhoonmkib"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Nasva", "typhoonmkib"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Zabel Ye", "typhoonmkib"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Novo", "typhoonmkib"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Nasva", "typhoonmkib"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Zabel Ye", "typhoonmkib"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Novo", "typhoonmkib"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Nasva", "typhoonmkib"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Zabel Ye", "typhoonmkib"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Novo", "typhoonmkib"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Nasva", "typhoonmkib"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Zabel Ye", "typhoonmkib"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Novo", "typhoonmkib"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Nasva", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Zabel Ye", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Novo", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Nasva", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Zabel Ye", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Novo", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Nasva", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Zabel Ye", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Novo", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Nasva", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Zabel Ye", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Novo", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Nasva", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Zabel Ye", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Novo", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Nasva", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Zabel Ye", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Novo", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Nasva", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Zabel Ye", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Novo", "spitfiremkixe"],
        ["Fighter Bomber Attack", "Veliki Rail Terminal", "Zabel Ye", "p47d22"],
        ["Fighter Bomber Attack", "Rojnova Bridges", "Zabel Ye", "p47d22"],
        ["Fighter Bomber Attack", "Kamenka Defenses", "Zabel Ye", "p47d22"],
        ["Fighter Bomber Attack", "Bubnova Rail", "Zabel Ye", "p47d22"],
        ["Fighter Bomber Attack", "Manistrova Rail Yard", "Zabel Ye", "p47d22"],
        ["Fighter Bomber Attack", "Philiptsevo Armored D", "Zabel Ye", "p47d22"],
        ["Fighter Bomber Attack", "Zaluchie Shipping", "Zabel Ye", "p47d22"],
        ["Tank Busters", "Rojnova Bridges", "Nasva", "a20b"],
        ["Tank Busters", "Rojnova Bridges", "Zabel Ye", "a20b"],
        ["Tank Busters", "Rojnova Bridges", "Novo", "a20b"],
        ["Tank Busters", "Kamenka Defenses", "Nasva", "a20b"],
        ["Tank Busters", "Kamenka Defenses", "Zabel Ye", "a20b"],
        ["Tank Busters", "Kamenka Defenses", "Novo", "a20b"],
        ["Tank Busters", "Bubnova Rail", "Nasva", "a20b"],
        ["Tank Busters", "Bubnova Rail", "Zabel Ye", "a20b"],
        ["Tank Busters", "Bubnova Rail", "Novo", "a20b"],
        ["Tank Busters", "Manistrova Rail Yard", "Nasva", "a20b"],
        ["Tank Busters", "Manistrova Rail Yard", "Zabel Ye", "a20b"],
        ["Tank Busters", "Manistrova Rail Yard", "Novo", "a20b"],
        ["Tank Busters", "Philiptsevo Armored D", "Nasva", "a20b"],
        ["Tank Busters", "Philiptsevo Armored D", "Zabel Ye", "a20b"],
        ["Tank Busters", "Philiptsevo Armored D", "Novo", "a20b"],
        ["Tank Busters", "Rojnova Bridges", "Nasva", "p51b5"],
        ["Tank Busters", "Rojnova Bridges", "Zabel Ye", "p51b5"],
        ["Tank Busters", "Rojnova Bridges", "Novo", "p51b5"],
        ["Tank Busters", "Kamenka Defenses", "Nasva", "p51b5"],
        ["Tank Busters", "Kamenka Defenses", "Zabel Ye", "p51b5"],
        ["Tank Busters", "Kamenka Defenses", "Novo", "p51b5"],
        ["Tank Busters", "Bubnova Rail", "Nasva", "p51b5"],
        ["Tank Busters", "Bubnova Rail", "Zabel Ye", "p51b5"],
        ["Tank Busters", "Bubnova Rail", "Novo", "p51b5"],
        ["Tank Busters", "Manistrova Rail Yard", "Nasva", "p51b5"],
        ["Tank Busters", "Manistrova Rail Yard", "Zabel Ye", "p51b5"],
        ["Tank Busters", "Manistrova Rail Yard", "Novo", "p51b5"],
        ["Tank Busters", "Philiptsevo Armored D", "Nasva", "p51b5"],
        ["Tank Busters", "Philiptsevo Armored D", "Zabel Ye", "p51b5"],
        ["Tank Busters", "Philiptsevo Armored D", "Novo", "p51b5"],
        ["Tank Busters", "Rojnova Bridges", "Nasva", "typhoonmkib"],
        ["Tank Busters", "Rojnova Bridges", "Zabel Ye", "typhoonmkib"],
        ["Tank Busters", "Rojnova Bridges", "Novo", "typhoonmkib"],
        ["Tank Busters", "Kamenka Defenses", "Nasva", "typhoonmkib"],
        ["Tank Busters", "Kamenka Defenses", "Zabel Ye", "typhoonmkib"],
        ["Tank Busters", "Kamenka Defenses", "Novo", "typhoonmkib"],
        ["Tank Busters", "Bubnova Rail", "Nasva", "typhoonmkib"],
        ["Tank Busters", "Bubnova Rail", "Zabel Ye", "typhoonmkib"],
        ["Tank Busters", "Bubnova Rail", "Novo", "typhoonmkib"],
        ["Tank Busters", "Manistrova Rail Yard", "Nasva", "typhoonmkib"],
        ["Tank Busters", "Manistrova Rail Yard", "Zabel Ye", "typhoonmkib"],
        ["Tank Busters", "Manistrova Rail Yard", "Novo", "typhoonmkib"],
        ["Tank Busters", "Philiptsevo Armored D", "Nasva", "typhoonmkib"],
        ["Tank Busters", "Philiptsevo Armored D", "Zabel Ye", "typhoonmkib"],
        ["Tank Busters", "Philiptsevo Armored D", "Novo", "typhoonmkib"],
        ["Tank Busters", "Rojnova Bridges", "Nasva", "spitfiremkixe"],
        ["Tank Busters", "Rojnova Bridges", "Zabel Ye", "spitfiremkixe"],
        ["Tank Busters", "Rojnova Bridges", "Novo", "spitfiremkixe"],
        ["Tank Busters", "Kamenka Defenses", "Nasva", "spitfiremkixe"],
        ["Tank Busters", "Kamenka Defenses", "Zabel Ye", "spitfiremkixe"],
        ["Tank Busters", "Kamenka Defenses", "Novo", "spitfiremkixe"],
        ["Tank Busters", "Bubnova Rail", "Nasva", "spitfiremkixe"],
        ["Tank Busters", "Bubnova Rail", "Zabel Ye", "spitfiremkixe"],
        ["Tank Busters", "Bubnova Rail", "Novo", "spitfiremkixe"],
        ["Tank Busters", "Manistrova Rail Yard", "Nasva", "spitfiremkixe"],
        ["Tank Busters", "Manistrova Rail Yard", "Zabel Ye", "spitfiremkixe"],
        ["Tank Busters", "Manistrova Rail Yard", "Novo", "spitfiremkixe"],
        ["Tank Busters", "Philiptsevo Armored D", "Nasva", "spitfiremkixe"],
        ["Tank Busters", "Philiptsevo Armored D", "Zabel Ye", "spitfiremkixe"],
        ["Tank Busters", "Philiptsevo Armored D", "Novo", "spitfiremkixe"],
        ["Tank Busters", "Rojnova Bridges", "Zabel Ye", "p47d22"],
        ["Tank Busters", "Kamenka Defenses", "Zabel Ye", "p47d22"],
        ["Tank Busters", "Bubnova Rail", "Zabel Ye", "p47d22"],
        ["Tank Busters", "Manistrova Rail Yard", "Zabel Ye", "p47d22"],
        ["Tank Busters", "Philiptsevo Armored D", "Zabel Ye", "p47d22"],
        ["Industrial Level Bomb", "Veliki Rail Terminal", "Nasva", "a20b"],
        ["Industrial Level Bomb", "Veliki Rail Terminal", "Zabel Ye", "a20b"],
        ["Industrial Level Bomb", "Veliki Rail Terminal", "Novo", "a20b"],
        ["Industrial Level Bomb", "Sopki Railyard", "Nasva", "a20b"],
        ["Industrial Level Bomb", "Sopki Railyard", "Zabel Ye", "a20b"],
        ["Industrial Level Bomb", "Sopki Railyard", "Novo", "a20b"],
        ["Industrial Level Bomb", "Toropets Rail", "Nasva", "a20b"],
        ["Industrial Level Bomb", "Toropets Rail", "Zabel Ye", "a20b"],
        ["Industrial Level Bomb", "Toropets Rail", "Novo", "a20b"],
        ["Industrial Level Bomb", "Bubnova Rail", "Nasva", "a20b"],
        ["Industrial Level Bomb", "Bubnova Rail", "Zabel Ye", "a20b"],
        ["Industrial Level Bomb", "Bubnova Rail", "Novo", "a20b"],
        ["Industrial Level Bomb", "Manistrova Rail Yard", "Nasva", "a20b"],
        ["Industrial Level Bomb", "Manistrova Rail Yard", "Zabel Ye", "a20b"],
        ["Industrial Level Bomb", "Manistrova Rail Yard", "Novo", "a20b"],
        ["Bridge Level Bomb", "Rojnova Bridges", "Nasva", "a20b"],
        ["Bridge Level Bomb", "Rojnova Bridges", "Zabel Ye", "a20b"],
        ["Bridge Level Bomb", "Rojnova Bridges", "Novo", "a20b"],
        ["Train Yard Level Bomb", "Veliki Rail Terminal", "Nasva", "a20b"],
        ["Train Yard Level Bomb", "Veliki Rail Terminal", "Zabel Ye", "a20b"],
        ["Train Yard Level Bomb", "Veliki Rail Terminal", "Novo", "a20b"],
        ["Train Yard Level Bomb", "Sopki Railyard", "Nasva", "a20b"],
        ["Train Yard Level Bomb", "Sopki Railyard", "Zabel Ye", "a20b"],
        ["Train Yard Level Bomb", "Sopki Railyard", "Novo", "a20b"],
        ["Train Yard Level Bomb", "Toropets Rail", "Nasva", "a20b"],
        ["Train Yard Level Bomb", "Toropets Rail", "Zabel Ye", "a20b"],
        ["Train Yard Level Bomb", "Toropets Rail", "Novo", "a20b"],
        ["Train Yard Level Bomb", "Bubnova Rail", "Nasva", "a20b"],
        ["Train Yard Level Bomb", "Bubnova Rail", "Zabel Ye", "a20b"],
        ["Train Yard Level Bomb", "Bubnova Rail", "Novo", "a20b"],
        ["Train Yard Level Bomb", "Manistrova Rail Yard", "Nasva", "a20b"],
        ["Train Yard Level Bomb", "Manistrova Rail Yard", "Zabel Ye", "a20b"],
        ["Train Yard Level Bomb", "Manistrova Rail Yard", "Novo", "a20b"],
        ["Tank Level Bomb", "Rojnova Bridges", "Nasva", "a20b"],
        ["Tank Level Bomb", "Rojnova Bridges", "Zabel Ye", "a20b"],
        ["Tank Level Bomb", "Rojnova Bridges", "Novo", "a20b"],
        ["Tank Level Bomb", "Kamenka Defenses", "Nasva", "a20b"],
        ["Tank Level Bomb", "Kamenka Defenses", "Zabel Ye", "a20b"],
        ["Tank Level Bomb", "Kamenka Defenses", "Novo", "a20b"],
        ["Tank Level Bomb", "Bubnova Rail", "Nasva", "a20b"],
        ["Tank Level Bomb", "Bubnova Rail", "Zabel Ye", "a20b"],
        ["Tank Level Bomb", "Bubnova Rail", "Novo", "a20b"],
        ["Tank Level Bomb", "Manistrova Rail Yard", "Nasva", "a20b"],
        ["Tank Level Bomb", "Manistrova Rail Yard", "Zabel Ye", "a20b"],
        ["Tank Level Bomb", "Manistrova Rail Yard", "Novo", "a20b"],
        ["Tank Level Bomb", "Philiptsevo Armored D", "Nasva", "a20b"],
        ["Tank Level Bomb", "Philiptsevo Armored D", "Zabel Ye", "a20b"],
        ["Tank Level Bomb", "Philiptsevo Armored D", "Novo", "a20b"],
        ["Close Air Support", "Veliki Rail Terminal", "Nasva", "p51b5"],
        ["Close Air Support", "Veliki Rail Terminal", "Zabel Ye", "p51b5"],
        ["Close Air Support", "Veliki Rail Terminal", "Novo", "p51b5"],
        ["Close Air Support", "Rojnova Bridges", "Nasva", "p51b5"],
        ["Close Air Support", "Rojnova Bridges", "Zabel Ye", "p51b5"],
        ["Close Air Support", "Rojnova Bridges", "Novo", "p51b5"],
        ["Close Air Support", "Kamenka Defenses", "Nasva", "p51b5"],
        ["Close Air Support", "Kamenka Defenses", "Zabel Ye", "p51b5"],
        ["Close Air Support", "Kamenka Defenses", "Novo", "p51b5"],
        ["Close Air Support", "Bubnova Rail", "Nasva", "p51b5"],
        ["Close Air Support", "Bubnova Rail", "Zabel Ye", "p51b5"],
        ["Close Air Support", "Bubnova Rail", "Novo", "p51b5"],
        ["Close Air Support", "Manistrova Rail Yard", "Nasva", "p51b5"],
        ["Close Air Support", "Manistrova Rail Yard", "Zabel Ye", "p51b5"],
        ["Close Air Support", "Manistrova Rail Yard", "Novo", "p51b5"],
        ["Close Air Support", "Philiptsevo Armored D", "Nasva", "p51b5"],
        ["Close Air Support", "Philiptsevo Armored D", "Zabel Ye", "p51b5"],
        ["Close Air Support", "Philiptsevo Armored D", "Novo", "p51b5"],
        ["Close Air Support", "Zaluchie Shipping", "Nasva", "p51b5"],
        ["Close Air Support", "Zaluchie Shipping", "Zabel Ye", "p51b5"],
        ["Close Air Support", "Zaluchie Shipping", "Novo", "p51b5"],
        ["Close Air Support", "Veliki Rail Terminal", "Nasva", "typhoonmkib"],
        ["Close Air Support", "Veliki Rail Terminal", "Zabel Ye", "typhoonmkib"],
        ["Close Air Support", "Veliki Rail Terminal", "Novo", "typhoonmkib"],
        ["Close Air Support", "Rojnova Bridges", "Nasva", "typhoonmkib"],
        ["Close Air Support", "Rojnova Bridges", "Zabel Ye", "typhoonmkib"],
        ["Close Air Support", "Rojnova Bridges", "Novo", "typhoonmkib"],
        ["Close Air Support", "Kamenka Defenses", "Nasva", "typhoonmkib"],
        ["Close Air Support", "Kamenka Defenses", "Zabel Ye", "typhoonmkib"],
        ["Close Air Support", "Kamenka Defenses", "Novo", "typhoonmkib"],
        ["Close Air Support", "Bubnova Rail", "Nasva", "typhoonmkib"],
        ["Close Air Support", "Bubnova Rail", "Zabel Ye", "typhoonmkib"],
        ["Close Air Support", "Bubnova Rail", "Novo", "typhoonmkib"],
        ["Close Air Support", "Manistrova Rail Yard", "Nasva", "typhoonmkib"],
        ["Close Air Support", "Manistrova Rail Yard", "Zabel Ye", "typhoonmkib"],
        ["Close Air Support", "Manistrova Rail Yard", "Novo", "typhoonmkib"],
        ["Close Air Support", "Philiptsevo Armored D", "Nasva", "typhoonmkib"],
        ["Close Air Support", "Philiptsevo Armored D", "Zabel Ye", "typhoonmkib"],
        ["Close Air Support", "Philiptsevo Armored D", "Novo", "typhoonmkib"],
        ["Close Air Support", "Zaluchie Shipping", "Nasva", "typhoonmkib"],
        ["Close Air Support", "Zaluchie Shipping", "Zabel Ye", "typhoonmkib"],
        ["Close Air Support", "Zaluchie Shipping", "Novo", "typhoonmkib"],
        ["Close Air Support", "Veliki Rail Terminal", "Nasva", "spitfiremkixe"],
        ["Close Air Support", "Veliki Rail Terminal", "Zabel Ye", "spitfiremkixe"],
        ["Close Air Support", "Veliki Rail Terminal", "Novo", "spitfiremkixe"],
        ["Close Air Support", "Rojnova Bridges", "Nasva", "spitfiremkixe"],
        ["Close Air Support", "Rojnova Bridges", "Zabel Ye", "spitfiremkixe"],
        ["Close Air Support", "Rojnova Bridges", "Novo", "spitfiremkixe"],
        ["Close Air Support", "Kamenka Defenses", "Nasva", "spitfiremkixe"],
        ["Close Air Support", "Kamenka Defenses", "Zabel Ye", "spitfiremkixe"],
        ["Close Air Support", "Kamenka Defenses", "Novo", "spitfiremkixe"],
        ["Close Air Support", "Bubnova Rail", "Nasva", "spitfiremkixe"],
        ["Close Air Support", "Bubnova Rail", "Zabel Ye", "spitfiremkixe"],
        ["Close Air Support", "Bubnova Rail", "Novo", "spitfiremkixe"],
        ["Close Air Support", "Manistrova Rail Yard", "Nasva", "spitfiremkixe"],
        ["Close Air Support", "Manistrova Rail Yard", "Zabel Ye", "spitfiremkixe"],
        ["Close Air Support", "Manistrova Rail Yard", "Novo", "spitfiremkixe"],
        ["Close Air Support", "Philiptsevo Armored D", "Nasva", "spitfiremkixe"],
        ["Close Air Support", "Philiptsevo Armored D", "Zabel Ye", "spitfiremkixe"],
        ["Close Air Support", "Philiptsevo Armored D", "Novo", "spitfiremkixe"],
        ["Close Air Support", "Zaluchie Shipping", "Nasva", "spitfiremkixe"],
        ["Close Air Support", "Zaluchie Shipping", "Zabel Ye", "spitfiremkixe"],
        ["Close Air Support", "Zaluchie Shipping", "Novo", "spitfiremkixe"],
        ["Close Air Support", "Veliki Rail Terminal", "Zabel Ye", "p47d22"],
        ["Close Air Support", "Rojnova Bridges", "Zabel Ye", "p47d22"],
        ["Close Air Support", "Kamenka Defenses", "Zabel Ye", "p47d22"],
        ["Close Air Support", "Bubnova Rail", "Zabel Ye", "p47d22"],
        ["Close Air Support", "Manistrova Rail Yard", "Zabel Ye", "p47d22"],
        ["Close Air Support", "Philiptsevo Armored D", "Zabel Ye", "p47d22"],
        ["Close Air Support", "Zaluchie Shipping", "Zabel Ye", "p47d22"]
      ]
    end
  end

  describe '#generate!' do
    it 'populates the cards table for all airforces' do
      cards = subject.generate!
      result = cards.map { |card| [card.title, card.area_of_operation, card.airfield, card.plane] }

      # TODO: Use a dummy protobuff config.
      # Even one form the small velikie campaign generates too many options at the moment to be used for testing
      expect(result.length).to eq 3354
    end
  end
end