allies:
  targets:
    - type: "ground units"
      areas_of_operation: 
        - "Gladbach Defences"
    - type: "industrial buildings"
      areas_of_operation:
        - "Cologne Marshaling Yard"
    - type: "trains"
      areas_of_operation:
        - "Cologne Marshaling Yard"
  planes: 
    - type: "p51d15"
      loadouts: "1..10"
      airfields:
        - name: "B-78 Eindhoven FSP"
          airforce: "RAF"
        - name: "Y-29 Asch FSP"
          airforce: "USAAF"
    - type: "p47d22"
      loadouts: "1..10"
      airfields:
        - name: "Y-29 Asch FSP"
          airforce: "USAAF"
    - type: "spitfiremkixe"
      loadouts: "1..10"
      airfields:
        - name: "B-78 Eindhoven FSP"
          airforce: "RAF"
    - type: "p38j25"
      loadouts: "1..10"
      airfields:
        - name: "B-78 Eindhoven BSP"
          airforce: "USAAF"
    - type: "a20b"
      loadoots: "1..10"
      airfields:
        - name: "B-78 Eindhoven BSP"
          airforce: "RAF"
axis:
  targets:
    - type: "tanks"
      areas_of_operation: 
        - "5th Armored"
    - type: "ground units"
      areas_of_operation:
        - "101st Airborne"
  planes: 
    - type: "fw190a8"
      loadouts: "1..10"
      airfields:
        - name: "Odendorf"
          airforce: "Luftwaffe"
        - name: "Kelz"
          airforce: "Luftwaffe"
    - type: "bf109g14"
      loadouts: "1..10"
      airfields:
        - name: "Odendorf"
          airforce: "Luftwaffe"
        - name: "Kelz"
          airforce: "Luftwaffe"
    - type: "he111h16"
      loadouts: "1..10"
      airfields:
        - name: "Ulmen Air Spawn"
          airforce: "Luftwaffe"