size: 60
allies:
  targets:
    - type: "ground units"
      areas_of_operation: 
        - "Gladbach Defences"
    - type: "industrial buildings"
      areas_of_operation:
        - "Cologne Marshaling Yard"
  planes: 
    - type: "p51d15"
      loadouts: "1..10"
      airfields:
        - name: "B-78 Eindhoven FSP"
          airforce: "RAF"
        - name: "Y-29 Asch FSP"
          airforce: "USAAF"
    - type: "p47d22"
      loadouts: "1..10"
      airfields:
        - name: "B-78 Eindhoven FSP"
          airforce: "RAF"
        - name: "Y-29 Asch FSP"
          airforce: "USAAF"
    - type: "spitfiremkixe"
      loadouts: "1..10"
      airfields:
        - name: "B-78 Eindhoven FSP"
          airforce: "RAF"
        - name: "Y-29 Asch FSP"
          airforce: "USAAF"
    - type: "p38j25"
      loadouts: "1..10"
      airfields:
        - name: "B-78 Eindhoven BSP"
          airforce: "RAF"
    - type: "a20b"
      loadoots: "1..10"
      airfields:
        - name: "B-78 Eindhoven BSP"
          airforce: "USAAF"
  
        